/* 🤖 this file was generated by svg-to-ts*/
export default {
  smallClose:
    '<svg width="12" height="12" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M3 3l6 6M3 9l6-6" stroke="currentColor" stroke-linecap="round"/></svg>'
};
